
version: 2

tables:
  - name: party
    tests:
      - excessive_validity_start_time_changes:
          PKs: party_id
          threshold: 500
          config:
            severity: warn
          tags:
            - excessive_validity_start_time_changes
      - excessive_validity_start_time_changes:
          PKs: party_id
          threshold: 1000
          config:
            severity: error
          tags:
            - excessive_validity_start_time_changes
    columns:
      - name: party_id
        tests:
        - dbt_utils.not_empty_string:
            trim_whitespace: true
      - name: (nationalities).region_code
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - valid_code:
            code_model: country_codes
            tags:
              - "country_codes"
        - not_null
      - name: residencies
        tests:
        - not_null ??
      - name: ((assets_value_range).start_amount).currency_code
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - not_null
        - valid_code:
            code_model: currency_codes
            tags:
              - "currency_codes"
        - single_value:
            tags:
              - "single_value"
      - name: ((assets_value_range).start_amount).units
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: int64
            tags:
              - "column_type"
        - dbt_utils.accepted_range:
              min_value: 0
              tags:
                - "accepted_range"
      - name: ((assets_value_range).start_amount).nanos
        tests:
        - dbt_utils.accepted_range:
              min_value: 0
              max_value: 999999999
              tags:
                - "accepted_range"
      - name: ((assets_value_range).end_amount).currency_code
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - not_null
        - valid_code:
            code_model: currency_codes
            tags:
              - "currency_codes"
        - single_value: --?
            tags:
              - "single_value"
      - name: ((assets_value_range).end_amount).units
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: int64
            tags:
              - "column_type"
        - not_null
        - dbt_utils.accepted_range:
              min_value: 0
              tags:
                - "accepted_range"
      - name: ((assets_value_range).end_amount).nanos
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: int64
            tags:
              - "column_type"
        - not_null
        - dbt_utils.accepted_range:
              min_value: 0
              max_value: 999999999
              tags:
                - "accepted_range"
  - name: account_party_link
    description: Account Party Link Table
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - account_id  
            - party_id 
            - validity_start_time
      - excessive_validity_start_time_changes:
          PKs: party_id, account_id
          threshold: 500
          config:
            severity: warn
          tags:
            - excessive_validity_start_time_changes  
      - excessive_validity_start_time_changes:
          PKs: party_id, account_id
          threshold: 1000
          config:
            severity: error
          tags:
            - excessive_validity_start_time_changes
  
    columns:
      - name: account_id
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - not_null
        - dbt_utils.not_empty_string:
            trim_whitespace: true
      - name: party_id
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: string
              tags:
              - "column_type"
          - relationships:
              to: ref("party")
              field: party_id
          - not_null
          - dbt_utils.not_empty_string:
              trim_whitespace: true
      - name: validity_start_time
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: timestamp
            tags:
              - "column_type"
        - not_null
      - name: source_system
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
      - name: is_entity_deleted
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: bool
            tags:
              - "column_type"
      - name: role
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - accepted_values:
            values: ['PRIMARY_HOLDER', 'SECONDARY_HOLDER', 'SUPPLEMENTARY_HOLDER']
  - name: transaction
    description: Transaction Table
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - transaction_id
            - validity_start_time 
      - excessive_validity_start_time_changes:
          PKs: transaction_id
          threshold: 500
          config:
            severity: warn
          tags:
            - excessive_validity_start_time_changes
      - excessive_validity_start_time_changes:
          PKs: transaction_id
          threshold: 1000
          config:
            severity: error
          tags:
            - excessive_validity_start_time_changes
    columns:
      - name: transaction_id
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - not_null
        - dbt_utils.not_empty_string:
            trim_whitespace: true
      - name: validity_start_time
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: timestamp
            tags:
              - "column_type"
        - not_null
      - name: source_system
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
      - name: account_id
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - relationships:
            to: ref("account_party_link")
            field: account_id
        - not_null
        - dbt_utils.not_empty_string:
            trim_whitespace: true
      - name: counterparty_account
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: struct
            tags:
              - "column_type"
      - name: (counterparty_account).account_id
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
      - name: type
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - not_null
        - dbt_utils.not_empty_string:
            trim_whitespace: true
        - accepted_values:
            values: ['WIRE', 'CASH', 'CHECK', 'CARD', 'OTHER']
      - name: direction
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - accepted_values:
            values: ['DEBIT', 'CREDIT']
        - not_null
        - dbt_utils.not_empty_string:
            trim_whitespace: true
      - name: book_time
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - is_even:
            tags:
              - "even"
      - name: normalized_booked_amount
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: struct
            tags:
              - "column_type"
      - name: (normalized_booked_amount).currency_code
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - valid_code:
            code_model: currency_codes
            tags:
              - "currency_codes"
        - single_value:
            tags:
              - "single_value"
      - name: (normalized_booked_amount).units
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: int64
            tags:
              - "column_type"
        - not_null
        - dbt_utils.accepted_range:
              min_value: 0
              tags:
                - "accepted_range"
      - name: (normalized_booked_amount).nanos
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: int64
            tags:
              - "column_type"
        - not_null
        - dbt_utils.accepted_range:
              min_value: 0
              max_value: 999999999
              tags:
                - "accepted_range"
      - name: is_entity_deleted
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: bool
            tags:
              - "column_type"
        - not_null
  - name: risk_case_event
    description: Risk Case Event Table
    columns:
      - name: risk_case_event_id
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - unique 
        - not_null
        - dbt_utils.not_empty_string:
            trim_whitespace: true
      - name: event_time
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: timestamp
            tags:
              - "column_type"
        - not_null
      - name: type
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - accepted_values:
            values: ['AML_SUSPICIOUS_ACTIVITY_START', 'AML_SUSPICIOUS_ACTIVITY_END','AML_PROCESS_START','AML_PROCESS_END','AML_ALERT_GOOGLE','AML_ALERT_LEGACY','AML_ALERT_ADHOC','AML_ALERT_EXPLORATORY','AML_SAR','AML_EXTERNAL','AML_EXIT']
        - not_null
        - dbt_utils.not_empty_string:
            trim_whitespace: true
      - name: party_id
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - not_null
        - dbt_utils.not_empty_string:
            trim_whitespace: true
        - relationships:
            to: ref("party")
            field: party_id
      - name: risk_case_id
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - not_null
        - dbt_utils.not_empty_string:
            trim_whitespace: true
      - name: is_entity_deleted
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: bool
            tags:
              - "column_type"

  - name: party_supplementary_data
    description: Party Supplementary Data Table
    optional: true
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - party_supplementary_data_id
            - party_id
            - validity_start_time 
    columns:
      - name: party_supplementary_data_id
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - unique 
        - not_null
        - dbt_utils.not_empty_string:
            trim_whitespace: true
      - name: validity_start_time
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: timestamp
            tags:
              - "column_type"
        - not_null
      - name: is_entity_deleted
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: bool
            tags:
              - "column_type"
        - not_null
      - name: source_system
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
      - name: party_id
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - not_null
      - name: supplementary_data_payload
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: struct
            tags:
              - "column_type"
      - name: supplementary_data_payload.value
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - not_null
