
version: 2

tables:
  - name: party
    columns:
      - name: party_id
        tests:
        - dbt_utils.not_empty_string:
            trim_whitespace: true
      - name: residencies
        tests:
        - not_null ??


  - name: party_supplementary_data
    description: Party Supplementary Data Table
    optional: true
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - party_supplementary_data_id
            - party_id
            - validity_start_time 
    columns:
      - name: party_supplementary_data_id
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - unique 
        - not_null
        - dbt_utils.not_empty_string:
            trim_whitespace: true
      - name: validity_start_time
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: timestamp
            tags:
              - "column_type"
        - not_null
      - name: is_entity_deleted
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: bool
            tags:
              - "column_type"
        - not_null
      - name: source_system
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
      - name: party_id
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - not_null
      - name: supplementary_data_payload
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: struct
            tags:
              - "column_type"
      - name: supplementary_data_payload.value
        tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: string
            tags:
              - "column_type"
        - not_null
